services:
  productservice:
    container_name: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5001:8080"
    env_file:
      - ProductService/.env
    depends_on:
      product_db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://productservice:5001/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    networks:
      - micro_net
  
  product_db:
    image: postgres:15
    container_name: product_db
    restart: always
    env_file:
      - ProductService/.env
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: Tienphat123
    #   POSTGRES_DB: demo_micro
    ports:
      - "5440:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d demo_micro || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
    networks:
      - micro_net

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - ApiGateway/.env
    # environment:
    #   GrpcEndpoints__ProductService: http://productservice:5001
    depends_on:
      - productservice
      # productservice:
      #   condition: service_healthy
    networks:
      - micro_net

volumes:
  product_db_data:
    
networks:
  micro_net:
    driver: bridge